spring.datasource.url=jdbc:postgresql://dpg-cub2iuvnoe9s73cvb2j0-a.oregon-postgres.render.com:5432/zebrian_db
spring.datasource.username=zebrian_db_user
spring.datasource.password=q1cP2zDS5Jo9gZj98TLWYclO6QzgVN1n
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect