spring.datasource.url=jdbc:postgresql://zebrian_db_user:q1cP2zDS5Jo9gZj98TLWYclO6QzgVN1n@dpg-d9n2lvrl550s7396ui90-a.oregon-postgres.render.com/zebrian_db
spring.datasource.username=zebrian_db_user
spring.datasource.password=q1cP2zDS5Jo9gZj98TLWYclO6QzgVN1n
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect