spring.datasource.url=psql -h db.czmroxdmyvzkzxqlppmh.supabase.co -p 5432 -d postgres -U postgres
spring.datasource.username=postgres
spring.datasource.password=prateek(2063)
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect